### ISSUE TITLE
Advanced JSON Build

### ISSUE THREAD

**Issue by neoaptt** [neoaptt/game#6]
One of my ideas was to make upgrade's and buildings be combined in the setup. You would have a json file

Here is the future of the json files. If the property is a string, then throw it through the equation parser. `[name]` will grab the properties of another upgrade. `displaySection` will group upgrades together. This way you can have an infinite amount of sections and order however you want. With the equation parser you can upgrade other upgrades with some simple math.

This is my ideal structure of the json file. It allows for the most out of the smallest amount of code. The hardest part is creating the equation parser.

`priority` will take one equation before the other. So if you want to hide then show or show then hide. That way if you have equations that contradict each other, you can chose how it handles it.

`amount` will set the initial amount of the item, I can see it mostly used for testing purposes.

```
{
    "title": "uGame Advanced",
    "upgrades": [
        {
            "name": "Combined",
            "base": 10,
            "upcost": 5,
            "increaseManual": 3,
            "increaseAutomation": 5,
            "displaySection":0
        },
        {
            "name": "Single",
            "base": 50,
            "amount": 5,
            "upcost": 20,
            "increaseAutomation": 5,
            "displaySection":1
        },
        {
            "name": "Equations",
            "base": 50,
            "amount": 0,
            "upcost": "base + 5 ^ amount",
            "increaseManual": "upcost * 0.1",
            "increaseAutomation": "base * increaseManual + 10",
            "displaySection":1
        },
        {
            "name": "Upgrade Other",
            "base": "[Single].base * [Single].amount",
            "increaseManual":"[Single].amount * amount",
            "displaySection":2
        },
        {
            "name": "Show",
            "show": "game.clicks > 1000 || [Upgrade Other].amount > 2",
            "hide": "game.multiplier < 100",
            "priority": "hide show",
            "base": 1000,
            "upcost": 500,
            "increaseManual": 250,
            "displaySection":0
        }
    ]
}


```

- [x] increaseAutomation + increaseManual on same upgrade
- [x] displaySection UI build
- [x] amount can be set
- [x] equation parser (this one might need to be broken out into smaller pieces it will be the hardest part)
- [x] tooltip from JSON file.

**Comment by TotomInc** [comment]
Thanks for explaining everything, it seems very clear now.

I will try to work on combining manual + automation.

**Comment by neoaptt** [comment]
Because there won't be a "buildings" and "upgrades" section of the UI, we need to create it. As far as the bootstrap goes. I would eventually try to stay clear of helpers like jquery and bootstrap. Thus making the game run faster and load quicker. Just a goal of mine. But bootstrap works fine.
![explain](https://cloud.githubusercontent.com/assets/9214528/13504559/09c71342-e143-11e5-9eea-fbf805cff798.png)

**Comment by TotomInc** [comment]
I think I understand how is your concept of `displaySection`, I will try my best to update the script.

**Comment by neoaptt** [comment]
Write now I'm working on the backend php / mysql server. I'm creating an SSL certificate and hosting on a domain.

**Comment by TotomInc** [comment]
For the project? I have not any knowledge about MySQL/PHP and other backend things like that, so I will not be able to create the uploading JSON file feature.

**Comment by neoaptt** [comment]
I'm most likely having to do most of the LAMP stack things on my own. What i will be doing is hosting api calls on http://www.neoaptt.tk/ and using that as our server.

**Comment by TotomInc** [comment]
I have pushed a new version which include everything on this issue but not equations (next thing I will work). UI still need improvements.

**Comment by neoaptt** [comment]
Man you fast, Good work! I'm still working on hosting.

**Comment by TotomInc** [comment]
Thanks. About equations, I have found a parser, [MathParser](http://jsfromhell.com/classes/math-parser), I started using it and it seems to be very simple, it would save us a lot of time if we use it, do you agree?

**Comment by neoaptt** [comment]
The only tricky part is the custom variables that match up to our object names.

**Comment by TotomInc** [comment]
I have some ideas of how to manage this. I also edited your issue and plan to add after equations a tooltip system.

**Comment by neoaptt** [comment]
sound good

**Comment by TotomInc** [comment]
I've just pushed another commit which introduce equation parser and its implementation on the script. It's not finished.

**Comment by neoaptt** [comment]
Sounds good, I'm working on the uploading scripts, allowing the user to upload and download JSON files.

**Comment by TotomInc** [comment]
Equation parser is slightly bugged, will work on it when I have some time.

**Comment by neoaptt** [comment]
I think I finally got it down pat. http://www.ugame.gq/ I'm going to do a little more with the DNS and SSL certificates. But I believe we can almost use it.

**Comment by TotomInc** [comment]
That's nice, I killed some bugs with the equation parser but there are still some bugs. I also added tooltip on JSON.

So right now the last thing is to kill bugs before releasing 1.0.0?

**Comment by TotomInc** [comment]
Oh I forgot to implement reference to other upgrades names on JSON : [name].base for example. Will be added ASAP.
