### ISSUE TITLE
Questions about win button feature.

### ISSUE THREAD

**Issue by TotomInc** [neoaptt/game#7]
I don't agree too much with the "win button" feature. If it's an incremental game, I think the win button doesn't have his place.

What do you wanted to implement about that? Did the win button was a "way" to soft-reset and get some prestige?

BTW, should we look about adding prestige feature on the game engine?

**Comment by neoaptt** [comment]
there should be a way to "win" if you choose to add it. All it is is a fancy reset button with a parameters behind it. The win button can have different features like a prestige feature and or a hard reset to the current game. Allowing the developer to chose how they want someone to win.

**Comment by TotomInc** [comment]
I have some ideas of how to implement a prestige system. The developer can choose first if he wants to add a prestige system. If yes, he can add his own formulas when earning prestige currency and the overall prestige multiplier (thanks to the equations parser).

Will work on this ASAP.

**Comment by neoaptt** [comment]
Sorry i'm not doing a lot on the projects ATM. I will work a little more on the server part tonight.

**Comment by TotomInc** [comment]
No problems!
