### ISSUE TITLE
Large Numbers

### ISSUE THREAD

**Issue by neoaptt** [neoaptt/game#8]
we will have to use some type of large number helper functions. Right now numbers can only get as big it a floating point value. We need to add a javascript class set that will handle large numbers for us. Allowing larger numbers and a more scallable game.

**Comment by TotomInc** [comment]
I use a beautify function in all of my projects, I'm going to implement it, it will take a few minutes.

**Comment by TotomInc** [comment]
Beautify functions added, everything works fine.
